### ISSUE TITLE
從後台開訂單，物流編碼會出不來

### ISSUE THREAD

**Issue by ChuyuHsu** [RicherYang/RY-WooCommerce-Tools#1]
我這邊遇到 從 wp-admin 後台開訂單
店號、電話都有填了
可是物流編碼出不來

情景: 
客人本來想用宅配，想一想又想換成超商取貨
我們為他修改訂單

**Comment by RicherYang** [comment]
已修正錯誤。請更新到最新的 1.0.4 版本。

在成功設定店家編號/取件人資訊後，須利用 **訂單動作** 當中的取得新物流編號 功能來獲取新的編號。

**Comment by ChuyuHsu** [comment]
感謝 馬上更新
