### ISSUE TITLE
藍新物流 IPN 回傳寫入的順序

### ISSUE THREAD

**Issue by nczz** [RicherYang/RY-WooCommerce-Tools#3]
由於更新訂單狀態在先，所以就算藍新 callback 回來的訂單資料有更新全家物流的資訊，也因為訂單狀態先改變，先觸發了發信而無法在通知訂單的信件的 hook 裡改寫收件的全家資訊。

所以 `woocommerce/gateways/newebpay/includes/newebpay-gateway-response.php` 這邊的 `payment_status_SUCCESS` 方法中，接收處理 `$ipn_info` 的段落順序是否可以調整到更新訂單狀態 `保留` 之上？

就是 `if (isset($ipn_info->StoreCode)) {}` 在  `if (!$order->is_paid()) {}` 前面這樣。

**Comment by RicherYang** [comment]
已經調整完成。
如果方便的話發送 PR 會更清楚
