### ISSUE TITLE
q-translateX filter error

### ISSUE THREAD

**Issue by depresto** [RicherYang/RY-WooCommerce-Tools#5]
目前遇到的問題為 ECpay CheckMacValue error

這個是會造成 CheckMacValue error 的 post message
09-16-2021 @ 14:42:34 - Checkout POST: array (
  'MerchantID' => '3216939',
  'MerchantTradeNo' => '26928TS04554771361',
  'MerchantTradeDate' => '2021/09/16 14:42:34',
  'PaymentType' => 'aio',
  'TotalAmount' => 280,
  'TradeDesc' => 'ANTOU Design',
  'ItemName' => '[:en]NOTA. A6 binder adaptor[:zh]NOTA. A6 整紙夾[:]',
  'ReturnURL' => 'https://www.antou1010.com/zh/wc-api/ry_ecpay_callback/',
  'ChoosePayment' => 'Credit',
  'ClientBackURL' => 'https://www.antou1010.com/zh/checkout/order-received/26928/?key=wc_order_FuzwHo8V5Rv78',
  'OrderResultURL' => 'https://www.antou1010.com/zh/checkout/order-received/26928/?key=wc_order_FuzwHo8V5Rv78',
  'NeedExtraPaidInfo' => 'Y',
  'IgnorePayment' => '',
  'EncryptType' => 1,
  'PaymentInfoURL' => 'https://www.antou1010.com/zh/wc-api/ry_ecpay_callback/',
  'ClientRedirectURL' => 'https://www.antou1010.com/zh/checkout/order-received/26928/?key=wc_order_FuzwHo8V5Rv78',
  'CheckMacValue' => 'D0C9454D2EC0E2496C8BB4007AA5DF795171447F3C6C3A0DC454E6D9923499F4',
)

這個是經過 filter [, ], : 後，成功結帳的 post message
09-16-2021 @ 14:44:45 - Generating payment form by ry_ecpay_credit for #26928
09-16-2021 @ 14:44:45 - Checkout POST: array (
  'MerchantID' => '3216939',
  'MerchantTradeNo' => '26928TS75864771361',
  'MerchantTradeDate' => '2021/09/16 14:44:45',
  'PaymentType' => 'aio',
  'TotalAmount' => 280,
  'TradeDesc' => 'ANTOU Design',
  'ItemName' => 'enNOTA. A6 binder adaptorzhNOTA. A6 整紙夾',
  'ReturnURL' => 'https://www.antou1010.com/zh/wc-api/ry_ecpay_callback/',
  'ChoosePayment' => 'Credit',
  'ClientBackURL' => 'https://www.antou1010.com/zh/checkout/order-received/26928/?key=wc_order_FuzwHo8V5Rv78',
  'OrderResultURL' => 'https://www.antou1010.com/zh/checkout/order-received/26928/?key=wc_order_FuzwHo8V5Rv78',
  'NeedExtraPaidInfo' => 'Y',
  'IgnorePayment' => '',
  'EncryptType' => 1,
  'PaymentInfoURL' => 'https://www.antou1010.com/zh/wc-api/ry_ecpay_callback/',
  'ClientRedirectURL' => 'https://www.antou1010.com/zh/checkout/order-received/26928/?key=wc_order_FuzwHo8V5Rv78',
  'CheckMacValue' => '5208794218685E2EBF6B70FF871F9ED37E09E109FE1E853D05977063A1D7648A',
)

非常感謝！

**Comment by RicherYang** [comment]
詭異，我嘗試將商品名稱修改為 `[:en]NOTA. A6 binder adaptor[:zh]NOTA. A6 整紙夾[:]` 然後進行結帳，是可以正確的計算 CheckMacValue ，所以應該還有其他的問題存在。

另外，你說的是 [qTranslate-X](https://wordpress.org/plugins/qtranslate-x/) 這款外掛嗎？
看起來已經被原作者放生了，所以就不特別進行相容性研究。

你目前就先暫時用你自製的過濾版程式，下一次更新外掛的時後，會提供於後台可以指定傳送給綠界的商品名稱的功能，那麼你用外掛調整商品名稱的問題就不會影響到金流的串接了。

**Comment by depresto** [comment]
沒錯，是 qTranslate-X 這個外掛沒錯

不過因為該外掛不好拔掉，暫時沒辦法拿掉這個過濾版程式，
還是非常感謝幫忙！

**Comment by RicherYang** [comment]
@depresto 請嘗試更新 RY WooCommerce Tools 版本 1.7.8
於綠界金流的設定畫面有新增 自訂金流商品名稱 ( payment item name ) 的設定
如果有設定值，與綠界串接的時候商品名稱就會使用該值，這樣你因為外掛改變商品名稱而導致 CheckMacValue  計算錯誤的問題就不會發生了。
