### ISSUE TITLE
綠界超商取貨未選擇門市也能結帳問題

### ISSUE THREAD

**Issue by mark2me** [RicherYang/RY-WooCommerce-Tools#6]
**環境：**
1. WooCommerce 6.5.1
2. RY WooCommerce Tools v1.9.6

**設定：**
1. WooCommerce: 運送方式->運送選項，「計算」只有勾選「在地址尚未輸入之前隱藏運送費用」

2. RY WooCommerce Tools 設定：金流：綠界貨到付款，物流：綠界超商取貨

**狀況步驟：**
1. 未註冊未登入的 user 選完商品，進入購物車，繼續下一步結帳。
2. 填寫個人資料
3. 運送方式：選擇超商取貨
4. 結帳方式：選擇貨到付款
5. 忘記去「選擇超商門市」、也沒有點選「運送到不同的地址」，直接結帳送出了，沒有顯示警告未選門市

**結果：**
1. 後台訂單資訊欄位的「運送地址」等於「帳單地址」
2. 編輯「運送地址」時，無法用地圖方式選擇超商，只能填入超商訊息，但一般人應該不知道超商代號之類的訊息。

`補充：是不是少了判斷 empty ?`
`function save_cvs_info($order, $data){
    if (!empty($data['CVSStoreID'])) {
       .....
    }
}`

**Comment by mark2me** [comment]
另外發現該狀況下，點選「選擇超商門市」也會出現
`Uncaught ReferenceError: RYECPaySendCvsPost is not defined`
沒有 load ry_shipping.js ，必須 reload 頁面後才會有，這時候運送地址自動打勾了，出現門市名稱、門市地址、門市電話

**Comment by RicherYang** [comment]
1. 目前建議「在地址尚未輸入之前隱藏運送費用」這一個項目不要勾選
他會導致選擇超商用的 JS 沒有載入，之後的相關錯誤算是這一錯誤的延伸錯誤。

2. 「RY WooCommerce Tools Pro」有提供後台選取超商門市的功能。

**Comment by mark2me** [comment]
OK，了解～

**Comment by RicherYang** [comment]
確定不修正這問題。

維持建議不要啟用「在地址尚未輸入之前隱藏運送費用」這一個功能。
