### ISSUE TITLE
RY Tools for WooCommerce 3.4.3 / WooCommerce 9.0.2 / 綠界金流錯誤

### ISSUE THREAD

**Issue by r3a2t10** [RicherYang/RY-WooCommerce-Tools#7]
環境：
WordPress 6.5.5
RY Tools for WooCommerce 3.4.3
WooCommerce 9.0.2

設定：
啟用綠界金流
啟用綠界物流

狀況步驟：
填寫完成物流（7-11／全家）
金流為信用卡結帳時，
綠界金流網站無法轉跳至信用卡填寫畫面，
而是顯示「未設定金流」。

> 交易失敗
> 訊息代碼：10200141
> 訊息說明：商店尚未提供任何付款方式，請聯繫商店處理。

一樣的金流設定在以下版號是可以通過綠界金流：
RY Tools for WooCommerce 1.12.4
WooCommerce 7.1.0

還請作者協助debug感恩><

<img width="941" alt="截圖 2024-07-06 下午9 37 04" src="https://github.com/RicherYang/RY-WooCommerce-Tools/assets/18047024/16d60c9c-f656-4dcf-83ad-ae1aa201cd88">
<img width="662" alt="截圖 2024-07-06 下午9 38 00" src="https://github.com/RicherYang/RY-WooCommerce-Tools/assets/18047024/5d32b4ee-b5de-4570-8ff0-5f2af42b6e99">
<img width="663" alt="截圖 2024-07-06 下午9 40 10" src="https://github.com/RicherYang/RY-WooCommerce-Tools/assets/18047024/ce659085-9b74-4475-aa3f-4598804f9909">
<img width="735" alt="截圖 2024-07-06 下午9 42 23" src="https://github.com/RicherYang/RY-WooCommerce-Tools/assets/18047024/39ce8934-a174-4982-b1c9-ade8df2c62d4">

**Comment by RicherYang** [comment]
這看起來一切符合預期並沒有錯誤。
因為是綠界方面拒絕進行交易，所以我並沒有辦法協助你解決問題。

如同截圖內容，是綠界拒絕該筆交易的進行 ( 該商店沒有對應的付款方式可使用 )，所以請與綠界聯繫，確認是商店的付款資格被封鎖，還是什麼問題原因導致他們拒絕交易。

另外，請確認金鑰是正確。
